apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  DB_HOST: "host.minikube.internal"
  DB_PORT: "3306"
  DB_NAME: "demo_db"
  DB_USER: "root"
  KAFKA_HOST: "host.minikube.internal"
  KAFKA_PORT: "9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
stringData:
  DB_PASS: "root"
